\version "2.16.1"

#(ly:set-option 'relative-includes #t)

\include "ilys/definitions.ily"
\include "ilys/clementi-op42-mid-L01-prel-cmaj.ily"
\include "ilys/clementi-op42-mid-L01-mozart.ily"
\include "ilys/clementi-op42-mid-L02-aria.ily"
\include "ilys/clementi-op42-mid-L03-handel.ily"
\include "ilys/clementi-op42-mid-L04-handel.ily"
\include "ilys/clementi-op42-mid-L05-handel.ily"
\include "ilys/clementi-op42-mid-L06-corelli.ily"
\include "ilys/clementi-op42-mid-L07-prel-amin.ily"
\include "ilys/clementi-op42-mid-L07-corelli.ily"
\include "ilys/clementi-op42-mid-L08-prel-fmaj.ily"
\include "ilys/clementi-op42-mid-L08-handel.ily"
\include "ilys/clementi-op42-mid-L09-handel.ily"
\include "ilys/clementi-op42-mid-L10-corelli.ily"
\include "ilys/clementi-op42-mid-L11-corelli.ily"
\include "ilys/clementi-op42-mid-L12-mozart.ily"
\include "ilys/clementi-op42-mid-L13-mozart-minuet.ily"
\include "ilys/clementi-op42-mid-L13-mozart-trio.ily"
\include "ilys/clementi-op42-mid-L14-couperin.ily"
\include "ilys/clementi-op42-mid-L15-prel-dmin.ily"
\include "ilys/clementi-op42-mid-L15-scarlatti.ily"
\include "ilys/clementi-op42-mid-L16-corelli.ily"
\include "ilys/clementi-op42-mid-L17-corelli.ily"
\include "ilys/clementi-op42-mid-L18-prel-gmaj.ily"
\include "ilys/clementi-op42-mid-L18-ah-vous.ily"
\include "ilys/clementi-op42-mid-L19-triste-raison.ily"
\include "ilys/clementi-op42-mid-L20-air-fal-lal-la.ily"
\include "ilys/clementi-op42-mid-L21-pleyel.ily"

